import type { LLMProvider, GenerateRequest } from "../../llmProvider";

function stableId(prefix: string, n: number) {
  return `${prefix}_${String(n).padStart(3, "0")}`;
}

export class MockLLMProvider implements LLMProvider {
  async generate(req: GenerateRequest) {
    if (req.phase === "Production" || req.phase === "Finalization") {
      const ir = {
        artifact: { id: stableId("artifact", 1), type: "report", title: "Cadence MVP", template: "default" },
        blocks: [
          { type: "titlePage", title: "Cadence MVP", subtitle: "Deterministic artifact compilation demo" },
          { type: "heading", level: 1, text: "Executive Summary" },
          { type: "paragraph", text: "This document was generated by the mock provider." },
          { type: "heading", level: 1, text: "Key Points" },
          { type: "bullets", items: ["Deterministic DOCX output", "ArtifactIR validation", "Workflow runner"] },
          { type: "pageBreak" },
          { type: "heading", level: 1, text: "Details" },
          { type: "paragraph", text: `Prompt: ${req.prompt}` },
          { type: "table", columns: ["Field", "Value"], rows: [["phase", req.phase], ["nodeCount", String(req.context.artifacts.length)]] },
        ],
      };
      return { output_json: JSON.stringify(ir) };
    }

    const out = {
      phase: req.phase,
      summary: `Mock output for ${req.phase}`,
      prompt: req.prompt,
      notes: ["Replace this provider with OpenAI/Anthropic to make it real."],
    };
    return { output_json: JSON.stringify(out) };
  }
}
