import type { LLMProvider, GenerateRequest } from "../../llmProvider";

function stableId(prefix: string, n: number) {
  return `${prefix}_${String(n).padStart(3, "0")}`;
}

export class MockLLMProvider implements LLMProvider {
  async generate(req: GenerateRequest) {
    if (req.phase === "Production" || req.phase === "Finalization") {
      const blockId = (n: number) => stableId("block", n);
      const ir = {
        artifact: { id: stableId("artifact", 1), type: "report", title: "Cadence MVP", template: "default" },
        blocks: [
          { id: blockId(1), type: "titlePage", title: "Cadence MVP", subtitle: "Deterministic artifact compilation demo" },
          { id: blockId(2), type: "heading", level: 1, text: "Executive Summary" },
          { id: blockId(3), type: "paragraph", text: "This document was generated by the mock provider." },
          { id: blockId(4), type: "heading", level: 1, text: "Key Points" },
          { id: blockId(5), type: "bullets", items: ["Deterministic DOCX output", "ArtifactIR validation", "Workflow runner"] },
          { id: blockId(6), type: "pageBreak" },
          { id: blockId(7), type: "heading", level: 1, text: "Details" },
          { id: blockId(8), type: "paragraph", text: `Prompt: ${req.prompt}` },
          { id: blockId(9), type: "table", columns: ["Field", "Value"], rows: [["phase", req.phase], ["nodeCount", String(req.context.artifacts.length)]] },
        ],
      };
      return { output_json: JSON.stringify(ir) };
    }

    if (req.phase === "Revision") {
      const patches = [
        {
          op: "replace",
          target: { kind: "block", id: "block_003" },
          value: { id: "block_003", type: "paragraph", text: "Revised via patch fixture." },
        },
      ];
      return { output_json: JSON.stringify({ patches }) };
    }

    const out = {
      phase: req.phase,
      summary: `Mock output for ${req.phase}`,
      prompt: req.prompt,
      notes: ["Replace this provider with OpenAI/Anthropic to make it real."],
    };
    return { output_json: JSON.stringify(out) };
  }
}
